### ISSUE TITLE
Potential incorrect license

### ISSUE THREAD

**Issue by peterbygrave** [conda-forge/libnsl-feedstock#4]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I think there is a mismatch in the license attributed to libnsl.

- The recipe folder list `libnsl` as being GPL-2.0: https://github.com/conda-forge/libnsl-feedstock/blob/master/recipe/meta.yaml#L33.
- The license file in the source repo is listed as LGPL: https://github.com/thkukuk/libnsl/blob/master/COPYING#L1

Would be great to get clarification.

Many thanks

**Comment by izahn** [comment]
This was my mistake, LGPL is correct.
